# Generated by Django 3.1 on 2021-05-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_auto_20210518_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('images', models.ImageField(upload_to='products')),
                ('price', models.IntegerField()),
                ('is_avilable', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('crated_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categorymodel')),
            ],
        ),
    ]
