# Generated by Django 3.1 on 2021-05-21 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_varlation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Varlation',
            new_name='Variation',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='varlation_category',
            new_name='variation_category',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='varlation_value',
            new_name='variation_value',
        ),
    ]
