# Generated by Django 3.1 on 2021-05-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
